### ISSUE TITLE
Thread error

### ISSUE THREAD

**Issue by character331** [keweimao/DeepDelight#5]
Process:
import os
from langchain.indexes import VectorstoreIndexCreator
from langchain.document_loaders import TextLoader

loader = TextLoader("FIFA.txt")
data = loader.load()
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 500, chunk_overlap = 0)
all_splits = text_splitter.split_documents(data)
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma

vectorstore = Chroma.from_documents(documents=all_splits, embedding=OpenAIEmbeddings())

Error:
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 8.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 10.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
---------------------------------------------------------------------------
RateLimitError                            Traceback (most recent call last)
<ipython-input-37-2c648badb2fb> in <cell line: 4>()
      2 from langchain.vectorstores import Chroma
      3 
----> 4 vectorstore = Chroma.from_documents(documents=all_splits, embedding=OpenAIEmbeddings())

18 frames
/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    761         stream_error = stream and "error" in resp.data
    762         if stream_error or not 200 <= rcode < 300:
--> 763             raise self.handle_error_response(
    764                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    765             )

RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by keweimao** [comment]
If you use OpenAI's APIs for this exercise, you will need a paid account and have active fund/quota in it. 

I suggested using open source/free models that you can run locally for this integration, for example: 
https://gpt4all.io/index.html

which appears to be lightweight and have good performance.

**Comment by lixiao-yang** [comment]
We choose to use GPT4ALL to bypass the OpenAI embeddings.
